export const INITIALIZE_LOCATION_WEATHER = 'INITIALIZE_LOCATION_WEATHER'
export const LOADING_LOCATION_WEATHER = 'LOADING_LOCATION_WEATHER'

export const LOADING_CURRENT_CITY_WEATHER = 'LOADING_CURRENT_CITY_WEATHER'
export const SUCCESS_CURRENT_CITY_WEATHER = 'SUCCESS_CURRENT_CITY_WEATHER'

export const SUCCESS_SAVE_CITY_WEATHER = 'SUCCESS_SAVE_CITY_WEATHER'